### ISSUE TITLE
key not displayed properly in configuration section

### ISSUE THREAD

**Issue by LeFl0w** [Linty-Services/sonar-coverage-ghdl#1]
Go to the configuration panel "code coverage" => "Gcov" => keys
The sonarqube key has not the right formatting it displays true instead of  sonar.gcov ...

![image](https://user-images.githubusercontent.com/11613152/66103520-54248980-e5b6-11e9-98e3-80674c0c43b1.png)

**Comment by mroca1** [comment]
Key display fixed in commit "Fix key name"
